### PR TITLE
Generated pull request for review & progress check

### PR DESCRIPTION
**Pull request by danhannigan**
Creating a pull request **mainly for review**  - just want to check in with you @txwkx and see if this is indeed the path you wanted me to go down for the scss. 

If so, there are some changes I'd already like to apply and some tidying to do.

But I wanted to get this in front of you before moving along further in case I was missing the mark. 

In reference to issue #1 

Todo (if it's the right track) 

- [ ] clean up comments
- [ ] possibly create folder structure inside 'css' to organize
- [ ] clean up variables and their usage

### CODE REVIEW

**Comment by txwkx** [comment]
@danhannigan Looks good to me :shipit:

**Comment by danhannigan** [comment]
Sweet @txwkx - I'll tidy some things up and re roll a pull request

**Comment by danhannigan** [comment]
Heads up - didn't forget about this, just got busy with work and life XD Will tackle this weekend.

**Comment by txwkx** [comment]
@danhannigan All good, no rush

**Comment by danhannigan** [comment]
Tidied it up - feel free to let me know if you want any further changes or not, otherwise should be good to go 👍

**Comment by txwkx** [comment]
@danhannigan Great! Could you, please, `git rebase` and squash the commits into a single one?

**Comment by danhannigan** [comment]
Alright @txwkx - my git skills are suck. I think I may have done it? My first mistake was not reading your contribution guide right. I can scrap this request if it's easer and follow along with what you have & make a pull request from my feature branch

**Comment by txwkx** [comment]
I changed the import statement, rebuild the bundle and now it's live and works like a charm! 🎉 

Big up @danhannigan!
Great work! Appreciate your effort

**Comment by danhannigan** [comment]
Awesome, thanks for letting me help. Feel free to hit me up if you need any further work like that done.

**Pull request merged**
